In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
d=pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\Data Science\\G-AI\\twcs.csv\\twcs.csv")

In [3]:
d.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2   
1      @sprintcare and how do you propose we do that               NaN   
2  @sprintcare I have sent several private messag...                 1   
3  @115712 Please send us a Private Message so th...                 3   
4                                 @sprintcare I did.                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [4]:
# Lower casing te text column

d['text']=d['text'].str.lower()

In [5]:
import re

In [6]:
def html_removal_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub("",text)

In [7]:
d["text"]=d["text"].apply(html_removal_tags)

In [8]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub("",text)

In [9]:
d['text']=d['text'].apply(remove_url)

In [10]:
import string

In [11]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [35]:
exclude=set(string.punctuation)
exclude

{'!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~'}

In [39]:
def remove_punc(text):
    # Remove punctuation characters
    text_no_punc = ''.join(char for char in text if char not in exclude)
    return text_no_punc

In [14]:
d['text']=d['text'].apply(remove_punc)

In [15]:
# spell correction

import textblob

In [16]:
chat_words={
   " AFAIK":"As Far As I Know",
"AFK": "Away From Keyboard",
"ASAP":"As Soon As Possible",
"BTW":"By The Way",
"B4":"Before",
"LAMO":"Laugh My A.. Off",
"FYI":"For your information"
}

def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [17]:
d['text']=d['text'].apply(chat_conversion)

In [18]:
from textblob import TextBlob

def spell_correction(text):
  obj=TextBlob(text)
  return obj.correct().string

In [19]:
# d['text']=d['text'].apply(spell_correction)

In [20]:
import nltk
from nltk.corpus import stopwords

def remove_stopwords(text):
    new_text=[]

    for word in text.split():
        if word in stopwords.words("english"):
            new_text.append("")
        else:
            new_text.append(word.strip())


    return " ".join(new_text).replace("   ","")

In [21]:
# Load stopwords once
stop_words = set(stopwords.words("english"))

def remove_stopwords_(text):
    # Split the text into words
    words = text.split()
    
    # Remove stopwords
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Join the filtered words back into a string
    filtered_text = " ".join(filtered_words)
    
    return filtered_text

In [22]:
d['text']=d['text'].apply(remove_stopwords_)

In [25]:
# pip install emoji

In [26]:
import emoji

def remove_emoji(text):
  clear_txt=emoji.demojize(text)
  return clear_txt

In [27]:
d['text']=d['text'].apply(remove_emoji)

In [28]:
d.shape

(2811774, 7)

In [29]:
d.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0  @115712 understand. would like assist you. wou...                 2   
1                                @sprintcare propose               NaN   
2  @sprintcare sent several private messages one ...                 1   
3  @115712 please send us private message assist ...                 3   
4                                   @sprintcare did.                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [36]:
exclude=set(string.punctuation)

In [40]:
d['text']=d['text'].apply(remove_punc)

In [41]:
d.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0  115712 understand would like assist you would ...                 2   
1                                 sprintcare propose               NaN   
2  sprintcare sent several private messages one r...                 1   
3  115712 please send us private message assist y...                 3   
4                                     sprintcare did                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [42]:
# deltetig the numbers from the text

def remove_numbers(text):
  removed_words=re.sub(r'\d+','',text)
  return removed_words

In [43]:
d['text']=d['text'].apply(remove_numbers)

In [44]:
d.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0   understand would like assist you would need g...                 2   
1                                 sprintcare propose               NaN   
2  sprintcare sent several private messages one r...                 1   
3   please send us private message assist you cli...                 3   
4                                     sprintcare did                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [55]:
# Lemmatization

from nltk.stem import WordNetLemmatizer

def lemmatization(text):
    words=text.split()

    lemmetizer=WordNetLemmatizer()

    lemetized_word=[lemmetizer.lemmatize(word) for word in words]
    
    return " ".join(lemetized_word)

In [56]:
d['text']=d['text'].apply(lemmatization)

In [58]:
d.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                                text response_tweet_id  \
0  understand would like assist you would need ge...                 2   
1                                 sprintcare propose               NaN   
2  sprintcare sent several private message one re...                 1   
3  please send u private message assist you click...                 3   
4                                     sprintcare did                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [59]:
d1=d.copy() # demonstrate word tokenization
d2=d.copy() # demonstrate sentence tokenization

# dataframe d demonstrates count vectorizer without tokenization

In [60]:
# tokenization can be done using split() OR using regular expressions or using NLTK
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize

In [64]:
# def wd_tk(text):
#     t_text=word_tokenize(text)
#     return t_text


# d1['text']=d1['text'].apply(wd_tk)


In [65]:
# def sen_tk(text):
#     t_text=word_tokenize(text)
#     return t_text


# d2['text']=d2['text'].apply(sen_tk)


In [66]:
# encoding using count vectorizer

from sklearn.feature_extraction.text import CountVectorizer

In [67]:
BOW=CountVectorizer()

In [68]:
document_matrix=BOW.fit_transform(d['text'])

In [70]:
document_matrix[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [71]:
BOW.vocabulary_

{'understand': 368828,
 'would': 395016,
 'like': 200388,
 'assist': 28216,
 'you': 400400,
 'need': 233635,
 'get': 142063,
 'private': 275798,
 'secured': 309635,
 'link': 201147,
 'sprintcare': 330492,
 'propose': 278034,
 'sent': 311399,
 'several': 313599,
 'message': 218502,
 'one': 249705,
 'responding': 294787,
 'usual': 374510,
 'please': 268356,
 'send': 311098,
 'click': 68411,
 'top': 358445,
 'profile': 277109,
 'did': 95515,
 'gain': 139017,
 'detail': 93711,
 'account': 2381,
 'worst': 394643,
 'customer': 83294,
 'service': 312195,
 'saddening': 303137,
 'hear': 156244,
 'shoot': 316304,
 'dm': 99669,
 'look': 205144,
 'kc': 188057,
 'gonna': 145678,
 'magically': 209934,
 'change': 61710,
 'connectivity': 75443,
 'whole': 389031,
 'family': 124483,
 'lyingface': 208532,
 'hundredpoints': 165361,
 'concern': 73875,
 'wed': 385392,
 'direct': 96885,
 'aa': 0,
 'since': 318934,
 'signed': 318195,
 'yousince': 401463,
 'day': 86785,
 'definitely': 89451,
 'work': 393573,
 

In [72]:
document_matrix[1].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [73]:
bigram=CountVectorizer(ngram_range=(2,2))

In [75]:
bigram_doc=bigram.fit_transform(d['text'])

In [76]:
bigram.vocabulary_

{'understand would': 5179491,
 'would like': 5540062,
 'like assist': 2788807,
 'assist you': 405641,
 'you would': 5611777,
 'would need': 5540357,
 'need get': 3233953,
 'get private': 2019254,
 'private secured': 3786922,
 'secured link': 4292134,
 'link assist': 2809622,
 'sprintcare propose': 4604768,
 'sprintcare sent': 4604964,
 'sent several': 4334904,
 'several private': 4370035,
 'private message': 3786802,
 'message one': 3059758,
 'one responding': 3419094,
 'responding usual': 4092924,
 'please send': 3684629,
 'send private': 4326497,
 'message assist': 3057429,
 'you click': 5606285,
 'click message': 956404,
 'message top': 3061050,
 'top profile': 5032357,
 'sprintcare did': 4603750,
 'message gain': 3058637,
 'gain detail': 1980725,
 'detail account': 1357573,
 'sprintcare worst': 4605501,
 'worst customer': 5533988,
 'customer service': 1203725,
 'saddening hear': 4196251,
 'hear please': 2216805,
 'please shoot': 3684688,
 'shoot dm': 4401596,
 'dm look': 1444878,
 

In [77]:
trigram=CountVectorizer(ngram_range=(3,3))

In [79]:
trigramdata=trigram.fit_transform(d["text"])

In [80]:
trigram.vocabulary_

In [81]:
mix=CountVectorizer(ngram_range=(1,2))
mix_vocab=mix.fit_transform(d["text"])

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [83]:
tfidf=TfidfVectorizer()

In [87]:
t=tfidf.fit_transform(d["text"])

In [88]:
t[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [89]:
tfidf.get_feature_names_out()  # vocabulary

array(['aa', 'aaa', 'aaaa', ..., '𝗘𝗥𝗜𝗖', '𝙨𝙥𝙚𝙘𝙞𝙛𝙞𝙘', '𝙨𝙩𝙚𝙥𝙨'],
      dtype=object)

In [90]:
len(tfidf.get_feature_names_out())

449705